In [13]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [14]:
data = pd.read_csv("Churn_Modelling.csv")

In [15]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [16]:
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)
#Irrelavant data

In [17]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [18]:
label_encoder_gender = LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [19]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [20]:
from sklearn.preprocessing import OneHotEncoder
# Initialize One-Hot Encoder
onehot_encoder_geo = OneHotEncoder(sparse_output=False)

# Fit and transform the Geography column
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']])

# Convert to DataFrame
geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography']),
    index=data.index
)

# Drop original Geography column and concatenate encoded columns
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [22]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [23]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [24]:
X = data.drop('Exited', axis = 1)
y = data['Exited']

In [25]:
X

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 12 columns]

In [26]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [28]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.250,random_state=42)

In [29]:
scaler= StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [30]:
X_train

array([[ 0.21835119,  0.91186722,  1.91661905, ...,  1.00053348,
        -0.57776083, -0.57735027],
       [ 2.05728037,  0.91186722,  0.20210899, ..., -0.99946681,
         1.73082   , -0.57735027],
       [ 0.75860157, -1.09665089, -0.75039661, ...,  1.00053348,
        -0.57776083, -0.57735027],
       ...,
       [ 0.86249588, -1.09665089, -0.08364269, ...,  1.00053348,
        -0.57776083, -0.57735027],
       [ 0.15601461,  0.91186722,  0.3926101 , ...,  1.00053348,
        -0.57776083, -0.57735027],
       [ 0.46769752,  0.91186722,  1.15461458, ..., -0.99946681,
         1.73082   , -0.57735027]])

In [32]:
with open('standard_scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [33]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [35]:
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), ##HL1 connect to input layer
    Dense(32,activation='relu'), #HL2
    Dense(1,activation='sigmoid')
])

WARNING:tensorflow:From c:\ANN_Classification_Project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [37]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [41]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [42]:
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [57]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [47]:
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [48]:
history = model.fit(
    X_train,y_train,validation_data=(X_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3326 - accuracy: 0.8639 - val_loss: 0.3503 - val_accuracy: 0.8596
Epoch 2/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3281 - accuracy: 0.8664 - val_loss: 0.3473 - val_accuracy: 0.8636
Epoch 3/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3281 - accuracy: 0.8660 - val_loss: 0.3424 - val_accuracy: 0.8628
Epoch 4/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3262 - accuracy: 0.8649 - val_loss: 0.3543 - val_accuracy: 0.8576
Epoch 5/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3253 - accuracy: 0.8692 - val_loss: 0.3496 - val_accuracy: 0.8640
Epoch 6/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3203 - accuracy: 0.8680 - val_loss: 0.3467 - val_accuracy: 0.8652
Epoch 7/100
235/235 [==============================] - 1s 5ms/step - loss: 0.3199 - accuracy: 0.8699 - val_loss: 0.3545 - val_accuracy: 0.8556
Epoch 8/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3155 - accuracy: 0.8688 - val_loss: 0.3511 - val_accuracy: 0.8596
Epoch 9/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3167 - accuracy: 0.8716 - val_loss: 0.3466 - val_accuracy: 0.8652
Epoch 10/100
235/235 [==============================] - 1s 4ms/step - loss: 0.3100 - accuracy: 0.8727 - val_loss: 0.3596 - val_accuracy: 0.8540
Epoch 11/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3085 - accuracy: 0.8731 - val_loss: 0.3514 - val_accuracy: 0.8632
Epoch 12/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3083 - accuracy: 0.8728 - val_loss: 0.3516 - val_accuracy: 0.8640
Epoch 13/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3053 - accuracy: 0.8740 - val_loss: 0.3580 - val_accuracy: 0.8604

In [49]:
model.save('model.h5')

c:\ANN_Classification_Project\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [58]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [63]:
%tensorboard --logdir logs/fit/